version: "3.9"

services:

  # Steedos Platform
  steedos:
    image: steedos/steedos-enterprise:2.5.17-beta.10
    container_name: steedos-enterprise
    ports:
      - "80:80"   
      - "443:443"
      - "9001:9001"
    environment:
      - ROOT_URL=http://127.0.0.1
      - STEEDOS_LICENSE=trial
    tty: true
    volumes:
      - "./storage:/steedos-storage"
    depends_on:
      oceanbase:
        condition: service_healthy

    
  oceanbase:
    image: oceanbase/oceanbase-ce
    healthcheck:
      test: ["CMD", "ob-mysql", "root"]
      interval: 30s
      timeout: 5s
      retries: 5
    ports: 
      - "2881:2881"
    volumes:
      - "./scripts:/root/scripts"
    environment:
      - MINI_MODE=1


# volumes:
#   oceanbase-data:
#     driver: local
#   steedos-data:
#     driver: local
#   steedos-mongodb-data:
#     driver: local
