# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5000
    onOpen: open-browser
    visibility: public
  - port: 3000
    onOpen: open-browser
    visibility: public
  - port: 6379
    onOpen: ignore
  - port: 27017
    onOpen: ignore
    visibility: public
# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Steedos
    init: |
      git config --global pull.rebase false
    command: |
      echo "ROOT_URL=$(gp url 5000)" >> .env.local
      echo "METADATA_SERVER=$(gp url 5000)" >> .env.local
      nvm i 14
      nvm use 14
      nvm alias default  14
      echo "nvm use default &>/dev/null" >> ~/.bashrc.d/51-nvm-fix
      npm i steedos-cli --global 

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - redhat.vscode-yaml
    - steedos.steedosdx-vscode
    - steedos.steedosdx-vscode-core
    - ms-ceintl.vscode-language-pack-zh-hans