image: ecr.aws.steedos.cn/dockerhub/steedos/gitpod-workspace-base:2.2.3

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5000
    onOpen: open-browser
    visibility: public
  - port: 3100
    onOpen: ignore
    visibility: public
  - port: 6379
    onOpen: ignore
  - port: 27017
    onOpen: ignore
    visibility: public
    
# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: MongoDB & Redis
    command: |
      docker-compose -f docker-compose-db.yml up
  - name: Steedos
    init: |
      git config --global pull.rebase false
    command: |
      echo "ROOT_URL=$(gp url 5000)" >> .env.local
      echo "STEEDOS_EXPERIENCE_URL=$(gp url 3100)" >> .env.local
      echo "METADATA_SERVER=$(gp url 5000)" >> .env.local
      npm i steedos-cli --global 
      yarn install
      gp await-port 27017
      gp await-port 6379
      yarn start

vscode:
  extensions:
    - redhat.vscode-yaml
    - steedos.steedosdx-vscode
    - steedos.steedosdx-vscode-core
    - ms-ceintl.vscode-language-pack-zh-hans
