version: "3.9"

services:

  steedos:
    image: steedos/steedos-community:2.4
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://host.docker.internal:27017/steedos
      - MONGO_OPLOG_URL=mongodb://host.docker.internal:27017/local
      - TRANSPORTER=redis://host.docker.internal:6379/1
      - CACHER=redis://host.docker.internal:6379
    # for dev
    entrypoint: ["/bin/sh", "-c" , "yarn && yarn dev"]
    volumes:
      - './steedos-app/:/app/steedos-app/:cached'
      - './steedos-packages/:/app/steedos-packages/:cached'
      - './.env:/app/.env:cached'
      - './package.json:/app/package.json:cached'
      - './steedos.config.js:/app/steedos.config.js:cached'