version: "3.9"

services:

  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-keycloak}
      - POSTGRES_USER=${POSTGRES_USER:-keycloak}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-keycloak}
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

  keycloak:
    image: steedos/keycloak
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_USER:-keycloak}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_PASSWORD:-keycloak}
      - PROXY_ADDRESS_FORWARDING=true
      - KC_HTTP_ENABLED=true
      - KC_PROXY=passthrough
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres/${POSTGRES_DB:-keycloak}
      - KC_DB_USERNAME=${POSTGRES_USER:-keycloak}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD:-keycloak}
      - KC_HOSTNAME=${KC_HOSTNAME}
      - KC_HOSTNAME_STRICT=false
      - KC_SPI_THEME_DEFAULT=steedos
    command:
      - "start"
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  redis:
    image: redis:6.2
    command: "redis-server --save \"\" --appendonly no --loglevel warning"
    ports:
      - "6379:6379"
  
  mongodb:
    image: 'bitnami/mongodb:4.4'
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_PORT_NUMBER=${MONGODB_PORT_NUMBER:-27017}
      - MONGODB_INITIAL_PRIMARY_HOST=${MONGODB_INITIAL_PRIMARY_HOST:-mongodb}
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}
      - MONGODB_REPLICA_SET_NAME=${MONGODB_REPLICA_SET_NAME:-steedos}
      - MONGODB_ENABLE_JOURNAL=${MONGODB_ENABLE_JOURNAL:-true}
      - MONGODB_ADVERTISED_HOSTNAME=${MONGODB_ADVERTISED_HOSTNAME:-mongodb}
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD:-yes}
    volumes:
      - 'steedos-mongo-data:/bitnami'

volumes:
  steedos-mongo-data:
      driver: local
  postgres_data:
      driver: local