version: "3.9"

services:
  rocketchat:
    image: rocketchat/rocket.chat:${RELEASE:-latest}
    restart: on-failure
    environment:
      MONGO_URL: mongodb://mongodb:27017/rocketchat
      MONGO_OPLOG_URL: mongodb://mongodb:27017/local
      ROOT_URL: http://localhost:3000
      PORT: 3000
      ADMIN_USERNAME: steedos
      ADMIN_NAME: steedos
      ADMIN_PASS: steedos
      ADMIN_EMAIL: steedos@example.com
      Accounts_TwoFactorAuthentication_Enabled: false
      OVERWRITE_SETTING_Show_Setup_Wizard: completed
      OVERWRITE_SETTING_Accounts_OAuth_Custom-Steedos: true
      OVERWRITE_SETTING_Accounts_OAuth_Custom-Steedos-url: https://id.steedos.cn
      OVERWRITE_SETTING_Accounts_OAuth_Custom-Steedos-token_path: /realms/master/protocol/openid-connect/token
      OVERWRITE_SETTING_Accounts_OAuth_Custom-Steedos-token_sent_via: header
      OVERWRITE_SETTING_Accounts_OAuth_Custom-Steedos-identity_path: /realms/master/protocol/openid-connect/userinfo
      OVERWRITE_SETTING_Accounts_OAuth_Custom-Steedos-authorize_path: /realms/master/protocol/openid-connect/auth
      OVERWRITE_SETTING_Accounts_OAuth_Custom-Steedos-id: steedos-oidc-public
      OVERWRITE_SETTING_Accounts_OAuth_Custom-Steedos-button_label_text: Login with Steedos ID
    depends_on:
      - mongodb   
    ports:
      - 3000:3000

  redis:
    image: redis:6.2
    command: "redis-server --save \"\" --appendonly no --loglevel warning"
    ports:
      - "6379:6379"
  
  mongodb:
    image: 'bitnami/mongodb:4.4'
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb
      - MONGODB_REPLICA_SET_NAME=steedos
      - MONGODB_ENABLE_JOURNAL=true
      - MONGODB_ADVERTISED_HOSTNAME=mongodb
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo admin -u root -p ${MONGODB_PASSWORD:-} --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - 'mongodb-data:/bitnami'

volumes:
  steedos-data: { driver: local }
  mongodb-data: { driver: local }
