version: "3.7"

services:
  rocketchat:
    image: rocketchat/rocket.chat:${RELEASE:-latest}
    restart: on-failure
    labels:
      traefik.enable: 'true'
      traefik.http.routers.rocketchat.rule: Host(`${DOMAIN}`)
      traefik.http.routers.rocketchat.tls: 'true'
      traefik.http.routers.rocketchat.entrypoints: https
      traefik.http.routers.rocketchat.tls.certresolver: le
    environment:
      MONGO_URL: "${MONGO_URL:-\
        mongodb://${MONGODB_ADVERTISED_HOSTNAME:-mongodb}:${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}/\
          ${MONGODB_DATABASE:-rocketchat}?replicaSet=${MONGODB_REPLICA_SET_NAME:-rs0}}"
      MONGO_OPLOG_URL: "${MONGO_OPLOG_URL:\
        -mongodb://${MONGODB_ADVERTISED_HOSTNAME:-mongodb}:${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}/\
          local?replicaSet=${MONGODB_REPLICA_SET_NAME:-rs0}}"
      ROOT_URL: ${ROOT_URL:-http://localhost:${HOST_PORT:-3000}}
      PORT: ${PORT:-3000}
      ADMIN_USERNAME: steedos
      ADMIN_NAME: steedos
      ADMIN_PASS: steedos
      ADMIN_EMAIL: steedos@example.com
      Accounts_TwoFactorAuthentication_Enabled: false
      OVERWRITE_SETTING_Show_Setup_Wizard: completed
      OVERWRITE_SETTING_Accounts_OAuth_Custom-Steedos: true
      OVERWRITE_SETTING_Accounts_OAuth_Custom-Steedos-url: https://id.steedos.cn
      OVERWRITE_SETTING_Accounts_OAuth_Custom-Steedos-token_path: /realms/master/protocol/openid-connect/token
      OVERWRITE_SETTING_Accounts_OAuth_Custom-Steedos-token_sent_via: header
      OVERWRITE_SETTING_Accounts_OAuth_Custom-Steedos-identity_path: /realms/master/protocol/openid-connect/userinfo
      OVERWRITE_SETTING_Accounts_OAuth_Custom-Steedos-authorize_path: /realms/master/protocol/openid-connect/auth
      OVERWRITE_SETTING_Accounts_OAuth_Custom-Steedos-id: steedos-oidc-public
      OVERWRITE_SETTING_Accounts_OAuth_Custom-Steedos-button_label_text: Login with Steedos ID
    depends_on:
      - mongodb   
    expose:
      - ${PORT:-3000}
    ports:
      - host_ip: ${BIND_IP:-0.0.0.0}
        target: ${PORT:-3000}
        published: ${HOST_PORT:-3000}
        protocol: tcp
        mode: host

  mongodb:
    image: docker.io/bitnami/mongodb:${MONGODB_VERSION:-4.4}
    restart: on-failure
    volumes:
      - mongodb_data5:/bitnami/mongodb
    ports:
      - 27017:27017
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: ${MONGODB_REPLICA_SET_NAME:-rs0}
      MONGODB_PORT_NUMBER: ${MONGODB_PORT_NUMBER:-27017}
      MONGODB_INITIAL_PRIMARY_HOST: ${MONGODB_INITIAL_PRIMARY_HOST:-mongodb}
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: ${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}
      MONGODB_ADVERTISED_HOSTNAME: ${MONGODB_ADVERTISED_HOSTNAME:-mongodb}
      MONGODB_ENABLE_JOURNAL: ${MONGODB_ENABLE_JOURNAL:-true}
      ALLOW_EMPTY_PASSWORD: ${ALLOW_EMPTY_PASSWORD:-yes}

volumes:
  mongodb_data5: { driver: local }
